services:
  - type: web
    name: bombay-engine
    env: python
    plan: free
    pythonVersion: 3.10.12
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
